In [2]:
import pandas as pd
import numpy as np

In [11]:
data = pd.read_excel(r"IC_data.xlsx", sheet_name=None)
columns = ['time', '415nm', '445nm', '480nm', '515nm', 'Clear', 'NIR', '555nm', '590nm', '630nm', '680nm', 'Clear.1', 'NIR.1']

In [15]:
print(f"Received following data:")
for sheet in data:
    data[sheet] = data[sheet][columns]
    display(data[sheet])

Received following data:

,time,415nm,445nm,480nm,515nm,Clear,NIR,555nm,590nm,630nm,680nm,Clear.1,NIR.1
0,0.00,1703,19196,20241,23631,65535,5442,18919,28318,20386,28200,65535,5444
1,0.66,1685,18970,20079,23678,65535,5439,19717,28633,20423,25226,65535,5374
2,1.32,1736,15827,17263,27566,65535,6052,28972,36114,25539,25290,65535,6144
3,1.99,1851,15779,17128,29176,65535,6028,31355,37151,25768,25069,65535,6038
4,2.65,1937,15842,17258,30477,65535,6106,33640,38931,26827,25362,65535,6134
...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,175.15,3321,16937,22442,43514,65535,8542,48707,58907,50546,41069,65535,8554
265,175.81,3321,16932,22430,43510,65535,8540,48715,58910,50555,41070,65535,8556
266,176.47,3325,16934,22448,43517,65535,8544,48721,58912,50535,41064,65535,8554
267,177.13,3322,16925,22444,43516,65535,8544,48762,58920,50563,41070,65535,8551
268,177.80,3324,16932,22447,43529,65535,8546,48731,58915,50552,41075,65535,8556

,time,415nm,445nm,480nm,515nm,Clear,NIR,555nm,590nm,630nm,680nm,Clear.1,NIR.1
0,0.00,1777,20091,20722,24291,65535,5448,19054,28714,20367,28770,65535,5454
1,0.66,1778,20086,20708,24298,65535,5450,19055,28695,20376,28780,65535,5454
2,1.33,1752,19688,20417,24308,65535,5439,19046,28580,20073,26034,65535,5270
3,1.99,1475,15992,17250,25836,65535,5222,21751,29348,20413,23678,65535,5312
4,2.65,1521,15874,17023,27158,65535,5308,22118,29404,20402,23571,65535,5304
...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,196.34,3442,18124,26607,45641,65535,8612,48296,58948,50501,40975,65535,8620
297,197.01,3443,18126,26596,45670,65535,8614,48339,58957,50548,41001,65535,8627
298,197.67,3446,18125,26605,45666,65535,8618,48331,58935,50520,41010,65535,8624
299,198.33,3445,18137,26610,45676,65535,8616,48349,58980,50530,41003,65535,8626
300,199.00,3445,18124,26627,45683,65535,8616,48365,58940,50556,41013,65535,8626

,time,415nm,445nm,480nm,515nm,Clear,NIR,555nm,590nm,630nm,680nm,Clear.1,NIR.1
0,REACTION REACTION REACTION,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,2146.0,22943.0,24846.0,26019.0,65535.0,5710.0,18583.0,23228.0,20265.0,32474.0,65535.0,5720.0
2,0.66,2149.0,22964.0,24877.0,26025.0,65535.0,5722.0,18584.0,23229.0,20262.0,32474.0,65535.0,5718.0
3,1.33,1864.0,17360.0,20111.0,26898.0,65535.0,5664.0,22052.0,25800.0,22155.0,24752.0,65535.0,5612.0
4,1.99,1731.0,14574.0,16791.0,29549.0,65535.0,5558.0,29199.0,28391.0,23076.0,23448.0,65535.0,5800.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,248.02,4821.0,17202.0,28574.0,59451.0,65535.0,10812.0,65535.0,65535.0,65535.0,51577.0,65535.0,10824.0
376,248.68,4822.0,17219.0,28584.0,59468.0,65535.0,10814.0,65535.0,65535.0,65535.0,51577.0,65535.0,10830.0
377,249.34,4821.0,17209.0,28592.0,59461.0,65535.0,10809.0,65535.0,65535.0,65535.0,51580.0,65535.0,10830.0
378,250,4819.0,17221.0,28583.0,59461.0,65535.0,10814.0,65535.0,65535.0,65535.0,51565.0,65535.0,10824.0
379,250.67,4820.0,17207.0,28580.0,59447.0,65535.0,10812.0,65535.0,65535.0,65535.0,51563.0,65535.0,10826.0

,time,415nm,445nm,480nm,515nm,Clear,NIR,555nm,590nm,630nm,680nm,Clear.1,NIR.1
0,0.00,2552,26788,28689,30592,65535,5716,20716,25018,22355,33626,65535,5722
1,0.66,2551,26783,28677,30585,65535,5716,20709,25003,22343,33622,65535,5720
2,1.32,2549,26790,28689,30589,65535,5720,20831,25001,22200,32233,65535,5631
3,1.99,1673,14046,16408,27611,65535,5214,27851,29697,24050,23015,65535,5716
4,2.65,2235,14071,16287,34447,65535,6064,40244,39933,30236,24172,65535,6322
...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,168.42,4901,16337,26364,59258,65535,10630,65535,65535,65535,50931,65535,10646
255,169.09,4899,16324,26354,59226,65535,10634,65535,65535,65535,50932,65535,10648
256,169.75,4902,16331,26362,59231,65535,10626,65535,65535,65535,50934,65535,10646
257,170.41,4900,16332,26366,59274,65535,10628,65535,65535,65535,50936,65535,10652
258,171.07,4900,16334,26373,59281,65535,10632,65535,65535,65535,50937,65535,10648

,time,415nm,445nm,480nm,515nm,Clear,NIR,555nm,590nm,630nm,680nm,Clear.1,NIR.1
0,0.00,3340,28834,34507,35644,65535,9832,35251,39792,35977,38197,65535,9838
1,0.66,3337,28823,34506,35641,65535,9830,35225,39779,35966,38189,65535,9834
2,1.33,3233,27606,33494,35493,65535,9747,37740,41316,36997,35011,65535,9892
3,1.99,3556,26293,32401,40112,65535,10600,48114,51110,44195,36936,65535,10776
4,2.65,3760,26433,32604,42313,65535,10800,50892,53254,45532,37227,65535,10864
...,...,...,...,...,...,...,...,...,...,...,...,...,...
334,221.56,4735,27191,36585,52172,65535,12496,60390,65380,61881,48781,65535,12507
335,222.22,4734,27178,36571,52161,65535,12490,60370,65357,61860,48746,65535,12506
336,222.88,4733,27173,36573,52140,65535,12486,60381,65372,61877,48781,65535,12508
337,223.54,4734,27176,36578,52138,65535,12482,60370,65350,61858,48766,65535,12506
338,224.21,4735,27179,36597,52153,65535,12494,60396,65374,61882,48786,65535,12512

In [7]:
data['k5b'].columns

Index(['time', '415nm', '445nm', '480nm', '515nm', 'Clear', 'NIR', '555nm',
       '590nm', '630nm', '680nm', 'Clear.1', 'NIR.1'],
      dtype='object')